src/menus/urls.py
from django.conf.urls import url
from .views import (
    ItemListView,
    ItemDetailView,
    ItemCreateView,
    ItemUpdateView,
)

urlpatterns = [
    url(r'^$', ItemListView.as_view(), name='list'),
    url(r'^create-menu-form/$', ItemCreateView.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(), name='detail'),
    # url(r'^(?P<pk>\d+)/$', ItemDetailView.as_view(), name='detail'),
]

src/myWebsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView,PasswordResetView, LogoutView
from profiles.views import ProfileFollowToggle, RegisterView, activate_user_view
from menus.views import HomeView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^activate/(?P<code>[a-z0-9].*)/$', activate_user_view, name='activate'),
    url(r'^reset-password', PasswordResetView.as_view(), name='password_reset'),
    url(r'^profile-follow/$', ProfileFollowToggle.as_view(), name='follow'),
    url(r'^restaurants/', include('restaurants.urls', namespace='restaurants')),
    url(r'^u/', include('profiles.urls', namespace='profiles')),
    url(r'^items/', include('menus.urls', namespace='menus')),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
]

src/restaurants/urls.py
from django.conf.urls import url
from restaurants.views import (
    RestaurantListView,
    RestaurantDetailView,
    RestaurantCreateView,
    RestaurantUpdateView
)

urlpatterns = [
    url(r'^$', RestaurantListView.as_view(), name='list'),
    url(r'^create-restaurant-form/$', RestaurantCreateView.as_view(), name='create'),
    url(r'^(?P<slug>[\w-]+)/$', RestaurantUpdateView.as_view(), name='detail'),
    # url(r'^(?P<slug>[\w-]+)/$', RestaurantDetailView.as_view(), name='detail'),
]

src/restaurants/models.py
from django.db import models
from django.db.models.signals import pre_save, post_save
from django.db.models import Q
from .utils import unique_slug_generator
from .validators import validate_category
from django.conf import settings
from django.core.urlresolvers import reverse
# Create your models here.


User = settings.AUTH_USER_MODEL


class RestaurantLocationQuerySet(models.QuerySet):
    def search(self, query):  # RestaurantLocation.objects.all.search(query='')
        if query:
            query = query.strip()
            return self.filter(
            Q(name__icontains=query)|
            Q(location__icontains=query)|
            Q(location__icontains=query)|
            Q(category__icontains=query)|
            Q(item__name__icontains=query)|
            Q(item__contents__icontains=query)
            ).distinct()
        return self


class RestaurantLocationManger(models.Manager):
    def get_queryset(self):
        return RestaurantLocationQuerySet(self.model, using=self._db)

    def search(self, query):  # RestaurantsLocation.objects.search()
        return self.search(query)


class RestaurantLocation(models.Model):
    owner = models.ForeignKey(User)
    name = models.CharField(max_length=120)
    location = models.CharField(max_length=120,null=True,blank=True)
    category = models.CharField(max_length=120,null=True,blank=False, validators=[validate_category])
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    slug = models.SlugField(null=True,blank=True)

    objects = RestaurantLocationManger()  # add Model.objects.all()

    def __str__(self):
        return self.name

    @property
    def title(self):
        return self.name

    def get_absolute_url(self):
        return reverse("restaurants:detail", kwargs={'slug': self.slug})


def rl_pre_save_receiver(sender, instance, *args, **kwargs):
    instance.category = instance.category.capitalize()
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


    # def rl_post_save_receiver(self, instance, created, *args, **kwargs):
    #     if not instance.slug:
    #         instance.slug = unique_slug_generator(instance)

pre_save.connect(rl_pre_save_receiver, sender=RestaurantLocation)

    # post_save.connect(rl_post_save_receiver,sender=RestaurantLocation)

src/restaurants/forms.py
from django import forms
from .models import RestaurantLocation
from .validators import validate_category


class RestaurantCreateForm(forms.Form):
    name = forms.CharField()
    location = forms.CharField(required=False)
    category = forms.CharField(required=False)


class RestaurantLocationCreateForms(forms.ModelForm):
    category = forms.CharField(required=False, validators=[validate_category])

    class Meta:
        model = RestaurantLocation
        fields = [
            'name',
            'location',
            'category',
            'slug',
        ]

src/restaurants/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView
from .models import RestaurantLocation
from .forms import RestaurantCreateForm, RestaurantLocationCreateForms
# Create your views here.


@login_required()
def restaurant_creatview(request):
    template_name = 'restaurants/create_restaurant_form.html'
    form = RestaurantLocationCreateForms(request.POST or None)
    errors = None
    if form.is_valid():
        if request.user.is_authenticated():
            instance = form.save(commit=False)
            instance.owner = request.user
            instance.save()
            return HttpResponseRedirect("/restaurants/")
        else:
            return HttpResponseRedirect("/login/")
    if form.errors:
        errors = form.errors
    context = {"form": form, "errors": errors}
    return render(request,template_name,context)


def restaurant_listview(request):
    template_name = 'restaurants/restaurantlocation_list.html'
    queryset = RestaurantLocation.objects.all()
    context = {
        "object_list": queryset
    }
    return render(request, template_name=template_name, context=context)


class RestaurantListView(LoginRequiredMixin, ListView):

    def get_queryset(self):
        return RestaurantLocation.objects.filter(owner=self.request.user)


class RestaurantDetailView(LoginRequiredMixin, DetailView):

    def get_queryset(self):
        return RestaurantLocation.objects.filter(owner=self.request.user)


class RestaurantCreateView(LoginRequiredMixin, CreateView):
    form_class = RestaurantLocationCreateForms
    login_url = '/login/'
    template_name = 'form.html'
    success_url = '/restaurants/'

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.owner = self.request.user
        return super(RestaurantCreateView, self).form_valid(form)

    def get_context_data(self, *args, **kwargs):
        context = super(RestaurantCreateView, self).get_context_data(**kwargs)
        context['title'] = 'Add Restaurant'
        return context


class RestaurantUpdateView(LoginRequiredMixin, UpdateView):
    form_class = RestaurantLocationCreateForms
    login_url = '/login/'
    template_name = 'restaurants/update-restaurant-form.html'
    success_url = '/restaurants/'

    def get_context_data(self, *args, **kwargs):
        context = super(RestaurantUpdateView, self).get_context_data(**kwargs)
        name = self.get_object().name
        context['title'] = f'Update Restaurant: {name}'
        return context

    def get_queryset(self):
        return RestaurantLocation.objects.filter(owner=self.request.user)

src/restaurants/templates/restaurants/restaurantlocation_detail.html
{% extends "base.html" %}
{% block head_title %} Restaurants|{{block.super}} {% endblock head_title %}

{% block content %}
<h1>{{ object.name }} <small>{{ object.category }}</small></h1>
<p>{{ object.location }}</p>
<p>{{ object.timestamp }}, updated {{ object.updated|timesince }} ago </p>
{% endblock content%}

src/restaurants/templates/restaurants/restaurantlocation_list.html
{% extends "base.html" %}
{% block head_title %} Restaurants|{{block.super}} {% endblock head_title %}

{% block content %}
<h1>My Restaurants<small><a href=" {% url 'restaurants:create'%}"> Add </a></small></h1>

<ul>
    {% for obj in object_list %}
    <li><a href='{{ obj.get_absolute_url }}'> {{obj.name}} </a><br/>
                {{obj.name}} | {{obj.name}} | {{obj.location}} |
                {{obj.category}} | {{obj.timestamp}} | {{obj.updated}}
    </li>
    {% empty %}
    <li><a href=" {% url 'restaurants:create'%}"> Add one </a></li>

    {% endfor %}
</ul>

{% endblock content%}

src/restaurants/templates/restaurants/restaurants_list.html
{% extends "base.html" %}
{% block head_title %} Restaurants|{{block.super}} {% endblock head_title %}</title>

{% block content %}
<h1>Restaurant List</h1>

<ul>
    {% for obj in object_list %}
            <li>{{obj.name}} <br>
                {{obj.name}} | {{obj.name}} | {{obj.location}} |
                {{obj.category}} | {{obj.timestamp}} | {{obj.updated}}
            </li>
    {% endfor %}
</ul>

{% endblock content%}

src/restaurants/templates/restaurants/update-restaurant-form.html
{% extends "base.html" %}
{% block head_title %} {{form.instance.name}}| Restaurants|{{block.super}} {% endblock head_title %}

{% block content %}
<h1>{{ form.instance.name }} <small>{{ form.instance.category }}</small></h1>
<p>{{ form.instance.location }}</p>
<p>{{ form.instance.timestamp }}, updated {{ form.instance.updated|timesince }} ago </p>

<hr/>
<h3>Make Changes</h3>
{% include 'snippets/form-snippet.html' with form=form %}
{% endblock content%}