src/menus/urls.py
from django.conf.urls import url
from .views import (
    ItemListView,
    ItemDetailView,
    ItemCreateView,
    ItemUpdateView,
)

urlpatterns = [
    url(r'^$', ItemListView.as_view(), name='list'),
    url(r'^create-menu-form/$', ItemCreateView.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(), name='detail'),
    # url(r'^(?P<pk>\d+)/$', ItemDetailView.as_view(), name='detail'),
]

src/myWebsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView,PasswordResetView, LogoutView
from profiles.views import ProfileFollowToggle, RegisterView, activate_user_view
from menus.views import HomeView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^activate/(?P<code>[a-z0-9].*)/$', activate_user_view, name='activate'),
    url(r'^reset-password', PasswordResetView.as_view(), name='password_reset'),
    url(r'^profile-follow/$', ProfileFollowToggle.as_view(), name='follow'),
    url(r'^restaurants/', include('restaurants.urls', namespace='restaurants')),
    url(r'^u/', include('profiles.urls', namespace='profiles')),
    url(r'^items/', include('menus.urls', namespace='menus')),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
]

src/templates/snippets/css.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"
      integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

src/templates/snippets/form-snippet.html
{% if form.errors.non_field_errors %}
{{ form.errors.non_field_errors }}
{% endif %}
<form method="POST"> {% csrf_token %}
    <!--<input type="text" name="name" placeholder="restaurant title"><br/>-->
    <!--<input type="text" name="location" placeholder="location"><br/>-->
    <!--<input type="text" name="category" placeholder="category"><br/>-->
    {{ form.as_p }}
    <button type="submit"> save </button>
</form>

src/templates/snippets/js.html
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity=
        "sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity=
        "sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity=
        "sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

src/templates/snippets/nav.html
<div class="container">
    <nav class="navbar navbar-default" style="border-radius: 10px">
        <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'home' %}">Restaurants.com</a>
        </div>
        <div class="navbar-toggler">
            <li> <a class="active" href="{% url 'home' %}"> Home</a></li>
            <li><a href="{% url 'about' %}"> About</a></li>
        <li><a href="{% url 'contact' %}"> Contact</a></li>
            {% if request.user.is_authenticated %}
        <li><a href="{% url 'restaurants:list' %}"> Restaurants </a></li>
        <li><a href="{% url 'menus:list' %}"> menu </a></li>
        <li><a href="{% url 'logout' %}"> Logout</a></li>
            {% else %}
        <li><a href="{% url 'login' %}"> Login </a></li>
        <li><a href="{% url 'register' %}"> Register</a></li>
            {% endif %}
        </div>
            </div>
    </nav>
</div>

src/templates/snippets/sidebar.html
<p>
    We are Awesome!
</p>